// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SinglyLinkedList from "./SinglyLinkedList.res.mjs";

console.log(SinglyLinkedList.sampleSinglyLinkedList);

export {
  
}
/*  Not a pure module */
