// Generated by ReScript, PLEASE EDIT WITH CARE


function makeNode(val) {
  return {
          value: val,
          next: undefined
        };
}

function append(l, newVal) {
  var n = l.next;
  var newNext = n !== undefined ? append(n, newVal) : ({
        value: newVal,
        next: undefined
      });
  return {
          value: l.value,
          next: newNext
        };
}

var sampleSinglyLinkedList = append(append(append({
              value: 1,
              next: undefined
            }, 2), 3), 4);

export {
  makeNode ,
  append ,
  sampleSinglyLinkedList ,
}
/* sampleSinglyLinkedList Not a pure module */
